version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/PacientHub

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=PacientHub
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local